import { useState } from "react";
import { View } from "react-native";
import {
  Badge,
  Button,
  Card,
  CardHeader,
  Input,
  ListItem,
  Screen,
  Tabs,
  Text,
} from "@finpilot/ui";
import {
  recommendBudget,
  type BudgetRecommendation,
  type Category,
} from "@finpilot/finance-engine";
import type { GeneratedBudget } from "@finpilot/ai-engine";
import { useMonthTotals, useSpendByCategory } from "../src/lib/hooks";
import { getActiveProvider, ON_DEVICE_HELP_MESSAGE } from "../src/lib/ai";
import { money, monthKey } from "../src/lib/format";

export default function BudgetScreen() {
  const month = monthKey();
  const totals = useMonthTotals(month);
  const spend = useSpendByCategory(month);

  const [goal, setGoal] = useState("");
  const [tab, setTab] = useState<"engine" | "ai">("engine");
  const [local, setLocal] = useState<BudgetRecommendation | null>(null);
  const [ai, setAi] = useState<GeneratedBudget | null>(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const income = totals.data?.income ?? 0;

  const history = (): Partial<Record<Category, number>> => {
    const h: Partial<Record<Category, number>> = {};
    for (const s of spend.data ?? []) h[s.category as Category] = s.amount;
    return h;
  };

  const plan = async () => {
    const savingsGoal = Number.parseFloat(goal.replace(/[^0-9.]/g, "")) || 0;
    setErr(null);
    // Always compute the deterministic engine recommendation.
    setLocal(recommendBudget({ monthlyIncome: income, savingsGoal, history: history() }));

    if (tab === "ai") {
      setBusy(true);
      try {
        const provider = await getActiveProvider();
        const result = await provider.generateBudget(
          { monthlyIncome: income, savingsGoal },
          (spend.data ?? []).map((s) => ({ category: s.category, amount: s.amount })),
        );
        setAi(result);
      } catch (e) {
        setErr(`${e instanceof Error ? e.message : String(e)}\n${ON_DEVICE_HELP_MESSAGE}`);
      } finally {
        setBusy(false);
      }
    }
  };

  return (
    <Screen>
      <Card>
        <CardHeader
          title="Plan a budget"
          subtitle={`Based on this month's income of ${money(income)}`}
        />
        <Input
          label="Monthly savings goal"
          keyboardType="decimal-pad"
          placeholder="500"
          value={goal}
          onChangeText={setGoal}
          left={<Text tone="muted">$</Text>}
        />
        <Tabs
          className="mt-3"
          items={[
            { key: "engine", label: "Engine" },
            { key: "ai", label: "AI" },
          ]}
          value={tab}
          onChange={(k) => setTab(k as "engine" | "ai")}
        />
        <Button
          label={tab === "ai" ? "Generate with AI" : "Calculate budget"}
          className="mt-3"
          loading={busy}
          onPress={() => void plan()}
        />
      </Card>

      {err ? (
        <Card className="mt-3 border-danger">
          <Text tone="danger" variant="caption">
            {err}
          </Text>
        </Card>
      ) : null}

      {/* Engine recommendation */}
      {local ? (
        <Card className="mt-3">
          <CardHeader
            title="Recommended plan"
            right={
              <Badge
                variant={local.goalFeasible ? "positive" : "warning"}
                label={local.goalFeasible ? "Feasible" : "Stretch"}
              />
            }
          />
          <View className="mb-2 flex-row items-center justify-between">
            <Text tone="muted">Recommended savings</Text>
            <Text variant="mono" tone="positive">
              {money(local.recommendedSavings)}
            </Text>
          </View>
          {local.allocations
            .filter((a) => a.amount > 0)
            .map((a) => (
              <ListItem key={a.category} title={a.category} value={money(a.amount)} />
            ))}
          {local.notes.length ? (
            <View className="mt-2 rounded-xl bg-muted p-3">
              {local.notes.map((n, i) => (
                <Text key={i} variant="caption" tone="muted">
                  • {n}
                </Text>
              ))}
            </View>
          ) : null}
        </Card>
      ) : null}

      {/* AI plan */}
      {tab === "ai" && ai ? (
        <Card className="mt-3">
          <CardHeader title="AI plan" subtitle="Generated by your provider" />
          <View className="mb-2 flex-row items-center justify-between">
            <Text tone="muted">Suggested savings</Text>
            <Text variant="mono" tone="positive">
              {money(ai.recommendedSavings)}
            </Text>
          </View>
          {ai.allocations.map((a, i) => (
            <ListItem key={`${a.category}-${i}`} title={a.category} value={money(a.amount)} />
          ))}
          {ai.notes.length ? (
            <View className="mt-2 rounded-xl bg-muted p-3">
              {ai.notes.map((n, i) => (
                <Text key={i} variant="caption" tone="muted">
                  • {n}
                </Text>
              ))}
            </View>
          ) : null}
        </Card>
      ) : null}
    </Screen>
  );
}
